/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.crypt.barada;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int generate=0x7f050004;
        public static final int new_key=0x7f050005;
        public static final int new_key_cancel=0x7f050002;
        public static final int new_key_confirm=0x7f050001;
        public static final int new_key_text=0x7f050000;
        public static final int pin=0x7f050003;
    }
    public static final class layout {
        public static final int key_entry=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int enter_key=0x7f04000b;
        public static final int enter_pin=0x7f040000;
        public static final int generate=0x7f040003;
        public static final int invalid_pin_text=0x7f040004;
        public static final int key_gen_check_message=0x7f040009;
        public static final int key_gen_check_title=0x7f040008;
        public static final int new_key=0x7f040007;
        public static final int new_key_cancel=0x7f04000c;
        public static final int new_key_confirm=0x7f04000a;
        public static final int non_integer_pin=0x7f040006;
        public static final int password=0x7f040002;
        public static final int password_dialog_title=0x7f040005;
    }
}
