/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.crypt.barada;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int header_text=0x7f040001;
        public static final int row_text=0x7f040000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int lock=0x7f020001;
    }
    public static final class id {
        public static final int cancel=0x7f060006;
        public static final int confirm=0x7f060005;
        public static final int generate=0x7f06000a;
        public static final int header=0x7f060000;
        public static final int icon=0x7f060007;
        public static final int key_label=0x7f060003;
        public static final int new_key_text=0x7f060004;
        public static final int new_profile_text=0x7f060002;
        public static final int pin_text=0x7f060009;
        public static final int profile_label=0x7f060001;
        public static final int profile_title=0x7f060008;
    }
    public static final class layout {
        public static final int profile_edit=0x7f030000;
        public static final int profile_list=0x7f030001;
        public static final int profile_row=0x7f030002;
        public static final int profile_use=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int cancel=0x7f05000d;
        public static final int confirm=0x7f05000e;
        public static final int edit_profile=0x7f050011;
        public static final int enter_key=0x7f05000b;
        public static final int enter_pin=0x7f050000;
        public static final int enter_profile=0x7f050012;
        public static final int generate=0x7f050003;
        public static final int invalid_pin_text=0x7f050004;
        public static final int key_gen_check_message=0x7f050009;
        public static final int key_gen_check_title=0x7f050008;
        public static final int new_key=0x7f050007;
        public static final int new_key_cancel=0x7f05000c;
        public static final int new_key_confirm=0x7f05000a;
        public static final int no_profile=0x7f05000f;
        public static final int non_integer_pin=0x7f050006;
        public static final int password=0x7f050002;
        public static final int password_dialog_title=0x7f050005;
        public static final int profile_add=0x7f050013;
        public static final int profile_delete=0x7f050014;
        public static final int use_profile=0x7f050010;
        public static final int version_name=0x7f050015;
    }
}
